name: "Code check"

on:
  workflow_call: null
  pull_request: null
  push:
    branches:
      - main

concurrency:
  group: larastrict-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a1834abbb49f67a0349bc29aad66e434c0441721
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "7.4", "8.0", "8.1", "8.2" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@a1834abbb49f67a0349bc29aad66e434c0441721
    secrets: inherit
    with:
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
      phpVersion: "${{ matrix.phpVersion }}"
